// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/bookmarks/data/local/bookmark_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8542772984841996240),
    name: 'BookmarkEntity',
    lastPropertyId: const obx_int.IdUid(7, 5892767454409296107),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8567576389194229962),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6980862471056114681),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2996858872217884918),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5968208247687853418),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4634236816202482171),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5176080626139921728),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5892767454409296107),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 8542772984841996240),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BookmarkEntity: obx_int.EntityDefinition<BookmarkEntity>(
      model: _entities[0],
      toOneRelations: (BookmarkEntity object) => [],
      toManyRelations: (BookmarkEntity object) => {},
      getId: (BookmarkEntity object) => object.id,
      setId: (BookmarkEntity object, int id) {
        object.id = id;
      },
      objectToFB: (BookmarkEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final urlOffset = fbb.writeString(object.url);
        final descriptionOffset = fbb.writeString(object.description);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, urlOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, tagsOffset);
        fbb.addInt64(5, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(6, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final object = BookmarkEntity(
          id: idParam,
          title: titleParam,
          url: urlParam,
          description: descriptionParam,
          tags: tagsParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BookmarkEntity] entity fields to define ObjectBox queries.
class BookmarkEntity_ {
  /// See [BookmarkEntity.id].
  static final id = obx.QueryIntegerProperty<BookmarkEntity>(
    _entities[0].properties[0],
  );

  /// See [BookmarkEntity.title].
  static final title = obx.QueryStringProperty<BookmarkEntity>(
    _entities[0].properties[1],
  );

  /// See [BookmarkEntity.url].
  static final url = obx.QueryStringProperty<BookmarkEntity>(
    _entities[0].properties[2],
  );

  /// See [BookmarkEntity.description].
  static final description = obx.QueryStringProperty<BookmarkEntity>(
    _entities[0].properties[3],
  );

  /// See [BookmarkEntity.tags].
  static final tags = obx.QueryStringVectorProperty<BookmarkEntity>(
    _entities[0].properties[4],
  );

  /// See [BookmarkEntity.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<BookmarkEntity>(
    _entities[0].properties[5],
  );

  /// See [BookmarkEntity.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<BookmarkEntity>(
    _entities[0].properties[6],
  );
}
